# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Test against all LTS versions.
        # NodeJS version support: https://nodejs.org/en/about/previous-releases
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn build
    - run: yarn ci
      env:
        CI: true

  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn audit

